server:
  port: 8099
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-driver
  redis:
    host: 192.168.127.10
    port: 6379
    database: 0